name: Release Management Workflow
run-name: Release Management Workflow
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    types:
      - opened
      - synchronized
      - closed
    branches:
      - develop
      - master
jobs:
  get_branch_specific_outputs:
    runs-on: [self-hosted, linux]
    outputs:
      version_namespace: ${{ steps.get_version_namespace.outputs.version_namespace }}
      latest_tag: ${{ steps.get_name_for_latest_tag.outputs.tag_name }}
    steps:
      - id: get_version_namespace
        name: Determine Version Namespace
        run: grep -q "master" <<< ${{ github.ref }} && echo "version_namespace=" >> $GITHUB_OUTPUT || echo "version_namespace=dev" >> $GITHUB_OUTPUT
      - id: get_name_for_latest_tag
        name: Get name for use with latest tag
        run: grep -q "master" <<< ${{ github.ref }} && echo "tag_name=latest" >> $GITHUB_OUTPUT || echo "tag_name=latest-dev" >> $GITHUB_OUTPUT
  release_management:
    runs-on: [self-hosted, linux]
    needs: get_branch_specific_outputs
    steps:
      - id: checkout_repo
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: debug
        name: Debug
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.event.action }}
          echo ${{ needs.get_branch_specific_outputs.outputs.version_namespace }}
          echo ${{ needs.get_branch_specific_outputs.outputs.latest_tag }}
      - id: get_semantic_version
        name: Get Semantic Version from git tag
        run: |
          latestDevTag="v.2.0.5-dev"
          removedSuffix="${latestDevTag%"dev"}"
          echo "${removedSuffix#"v"}"
      - id: get_semantic_version_prod
        name: Get Semantic Version from git tag
        run: |
          latestDevTag="v.1.0.5"
          removedSuffix="${latestDevTag%"dev"}"
          echo "${removedSuffix#"v"}"
      # - id: bump_dev_version
      #   name: Bump dev tag
      #   uses: christian-draeger/increment-semantic-version@1.0.3
      #   with:
      #     current-version: 'v2.0.5-dev'
      #     version-fragment: 'feature'
      # - id: bump_version
      #   name: Bump prod tag
      #   uses: christian-draeger/increment-semantic-version@1.0.3
      #   with:
      #     current-version: 'v1.0.5'
      #     version-fragment: 'feature'